export scripts for imdb_wiki data
reductstore/datasets pull request #1
Opened 2023-04-09 22:17 UTC by johndon98

2023-04-10 07:42 UTC, atimin requested changes

2023-04-10 07:42 UTC, atimin commented on export/imdb/export.py
> +                        label = meta_data_list[i]
Didn't manage to make it work. `if image == img_in_meta_data` is always false. I need the images with metadata so if there is no one, then skip image. Moreover, it is very slow. You use a list of dictionaries and search in the loop again and again. It takes 1 second on my laptop. So, the whole export could take 5 days... Try to change your `mat_to_dict` function and return a dictionary where the key is a filename and the value is metadata.

2023-04-10 07:42 UTC, atimin commented on export/imdb/export.py
> +                    'label': label
if the `lable` variables is already a dictionary use it directly:

```
await bucket.write(REDUCT_STORE_ENTRY + dataset_name, img_data, timestamp=counter, labels=label,
                                   content_type="image/jpg")
```

2023-04-10 20:35 UTC, johndon98 commented on utils/meta_data_parser.py
> +    for row in pd.DataFrame(file).to_dict('records'):
Here, I convert a dict with values as arrays into a dataframe and then obtain a dict of dicts (where each dict is a row of the dataframe). This way meta data for each image is in the inner_dicts within one larger dict.

2023-04-10 20:37 UTC, johndon98 commented on utils/meta_data_parser.py
> +        meta_data_dict[row['full_path'][3:]] = row
Here I use the filename of the image as key and the values are inner_dicts containing meta data of each image.

2023-04-10 20:59 UTC, johndon98 commented on utils/meta_data_parser.py
> +    for row in pd.DataFrame(file).to_dict('records'):
Is there a faster way to obtain this structure {filename: {meta_data}} ?
Please let me know if you have suggestions to obtain the desired final format using a different method.
I am not sure if converting a dict (with arrays as values) to dataframe and then back to individual dict is the most efficient way. @atimin

2023-04-11 16:01 UTC, atimin approved these changes

2023-04-11 16:01 UTC, atimin commented on utils/meta_data_parser.py
> +        meta_data_dict[row['full_path'][3:]] = row
It should be more efficient than manual search in a loop. You can also see it if you run it locally. If you didn't manage to setup an instance locally, I can provide a bucket for testing on https://play.reduct.store

2023-04-11 17:59 UTC, johndon98 commented on utils/meta_data_parser.py
> +        meta_data_dict[row['full_path'][3:]] = row
Yes, I already did a test run. I setup reductstore locally using the docker image. Then I created a bucket and wrote the image files into this bucket. This is how I got to know it took approx. 2 hours for 30GB. 
Let me know if the export is faster for you now.

2023-04-11 18:33 UTC, atimin commented on utils/meta_data_parser.py
> +        meta_data_dict[row['full_path'][3:]] = row
2 hours is ok, I think. I'll optimize it later if it is necessary. Let me try it on my side , and we're done. Thank you!

2023-04-11 19:19 UTC, johndon98 commented on utils/meta_data_parser.py
> +        meta_data_dict[row['full_path'][3:]] = row
Yes, sounds good. Thank you.

2023-04-12 18:28 UTC, merged